version: "3.8"

services:
  #
  # gateway
  #
  gw01:
    image: "openresty/openresty:alpine"
    ports:
      - "80:80"
    volumes:
      - "./share/gw/nginx:/etc/nginx"
    networks:
      - "gw2kc"
      - "gw2srv"
  #
  # keycloak
  #
  kc01:
    image: "jboss/keycloak"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "pass"
      DB_ADDR: "db"
      DB_PORT: "5432"
      DB_DATABASE: "keycloak"
      DB_VENDOR: "postgres"
      DB_USER: "kc"
      DB_PASSWORD: "pass"
    ports:
      - "8080:8080"
    networks:
      - "gw2kc"
      - "kc2db"
  #
  # database for keycloak
  #
  db:
    image: "postgres:13.0-alpine"
    environment:
      POSTGRES_USER: "kc"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "keycloak"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - "./share/db:/var/lib/postgresql/data"
    networks:
      - "kc2db"
  #
  # service
  #
  srv01:
    image: "service"
    volumes:
      - "./share/srv01:/data"
    environment:
      JSON_SERVER_PORT: "80"
    networks:
      - "gw2srv"
  #
  srv02:
    image: "service"
    volumes:
      - "./share/srv02:/data"
    environment:
      JSON_SERVER_PORT: "80"
    networks:
      - "gw2srv"
  #
  srv03:
    image: "service"
    volumes:
      - "./share/srv03:/data"
    environment:
      JSON_SERVER_PORT: "80"
    networks:
      - "gw2srv"

networks:
  gw2kc:
  kc2db:
  gw2srv:

