version: "3.8"

services:
  #
  # gateway
  #
  gw01:
    image: "api_gateway"
    volumes:
      - "./share/gw01/nginx.conf/:/etc/nginx/nginx.conf"
      - "./share/gw01/conf.d/:/etc/nginx/conf.d"
      - "./share/gw01/main.lua:/usr/local/openresty/main.lua"
    networks:
      - "gw2kc"
      - "gw2srv"
    ports:
      - "80:80"
  #
  # keycloak
  #
  kc01:
    image: "jboss/keycloak:11.0.3"
    environment:
      KEYCLOAK_LOGLEVEL: "INFO"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "pass"
      DB_ADDR: "kc01db"
      DB_PORT: "5432"
      DB_DATABASE: "keycloak"
      DB_VENDOR: "postgres"
      DB_USER: "kc"
      DB_PASSWORD: "pass"
    ports:
      - "8080:8080"
    networks:
      - "gw2kc"
  #
  # database for keycloak
  #
  kc01db:
    image: "postgres:13.0-alpine"
    environment:
      POSTGRES_USER: "kc"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "keycloak"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - "kc01db:/var/lib/postgresql/data"
    networks:
      - "gw2kc"
  #
  # service
  #
  srv01:
    image: "service"
    volumes:
      - "./share/srv01:/data"
    environment:
      JSON_SERVER_PORT: "80"
    networks:
      - "gw2srv"
    ports:
      - "3000:80"
  #
  srv02:
    image: "service"
    volumes:
      - "./share/srv02:/data"
    environment:
      JSON_SERVER_PORT: "80"
    networks:
      - "gw2srv"
  #
  srv03:
    image: "service"
    volumes:
      - "./share/srv03:/data"
    environment:
      JSON_SERVER_PORT: "80"
    networks:
      - "gw2srv"

networks:
  gw2kc:
  gw2srv:

volumes:
  kc01db:

